<a href="https://colab.research.google.com/github/blindt05/AiIntroductionUdemy/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [3]:
import numpy as np
np.__version__

'2.0.2'

In [5]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

1D Array

In [7]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [8]:
print(x)

[1 2 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(3,)

In [12]:
x.size

3

In [13]:
x.dtype

dtype('int64')

In [16]:
x = np.array([1.3, 2.3, 3.4])
print(x)

[1.3 2.3 3.4]


In [17]:
x.dtype

dtype('float64')

2D Array

In [19]:
x = np.array([[1,2],[-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [24]:
x.shape

(2, 3)

3D Array

In [28]:
x = np.array(
    [[[4, 3, 2],
      [3, 2, 1]],
     [[1, 1, 1],
      [2, 2, 2]],
     [[2, 3, 4],
      [3, 3, 2]],
     ]
)
print(x)

[[[4 3 2]
  [3 2 1]]

 [[1 1 1]
  [2 2 2]]

 [[2 3 4]
  [3 3 2]]]


In [30]:
x.ndim

3

In [31]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [33]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [34]:
x = np.array([1.1, 2, 3])
x.dtype

dtype('float64')

In [36]:
x = np.array([1, 2, 3], dtype='float')
x.dtype

dtype('float64')

In [37]:
x = np.array([1, 2, 3], dtype='complex')
x.dtype

dtype('complex128')

In [39]:
x = np.array([1.2, 2, 3], dtype='int')
x.dtype

dtype('int64')

In [40]:
x

array([1, 2, 3])

In [41]:
x = np.array([True, False])
x.dtype

dtype('bool')

In [50]:
x = np.array([24, 120, 110], dtype=np.int8)
x.dtype

dtype('int8')

In [51]:
x = np.array([24, 120, 230], dtype=np.uint8)
x.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [55]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
np.zeros(shape=(4,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.ones(shape=(5,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [60]:
np.full(shape=(3,3), fill_value=5, dtype="int")

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [63]:
np.arange((10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [67]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [70]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [71]:
np.linspace(start=0, stop=10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [75]:
x.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
x.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [78]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, -5, 1])
print(x)
print(y)

[1 2 3 4]
[ 2  4 -5  1]


In [79]:
x + y

array([ 3,  6, -2,  5])

In [80]:
x - y

array([-1, -2,  8,  3])

In [81]:
x * y

array([  2,   8, -15,   4])

In [82]:
x / y

array([ 0.5,  0.5, -0.6,  4. ])

In [83]:
x + 3

array([4, 5, 6, 7])

In [86]:
x * 2

array([2, 4, 6, 8])

In [87]:
x + 3 * y

array([  7,  14, -12,   7])

In [88]:
np.add(x, y)

array([ 3,  6, -2,  5])

In [90]:
np.subtract(x, y)

array([-1, -2,  8,  3])

In [91]:
np.divide(x, y)

array([ 0.5,  0.5, -0.6,  4. ])

In [92]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 5], [2, 2]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 5]
 [2 2]]


In [93]:
x * y

array([[ 5, 10],
       [ 6,  8]])

In [95]:
np.dot(x, y)

array([[ 9,  9],
       [23, 23]])

In [97]:
y.dot(x)

array([[20, 30],
       [ 8, 12]])

In [98]:
x.dot(y)

array([[ 9,  9],
       [23, 23]])

In [99]:
x @ y

array([[ 9,  9],
       [23, 23]])

In [100]:
y @ x

array([[20, 30],
       [ 8, 12]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [101]:
np.random.seed(0)

In [102]:
np.random.randn()

1.764052345967664

In [118]:
np.random.randn(10)

array([-0.37992245,  0.25973465, -1.68134864, -0.91679481, -0.1192241 ,
       -0.44627728, -2.14335544,  0.01003777, -0.55822259,  0.48090565])

In [104]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [106]:
np.random.rand()

0.7392635793983017

In [107]:
np.random.rand(10)

array([0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
       0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660145])

In [108]:
np.random.rand(10, 2)

array([[0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293],
       [0.02010755, 0.82894003],
       [0.00469548, 0.67781654],
       [0.27000797, 0.73519402],
       [0.96218855, 0.24875314]])

In [109]:
np.random.randint(10)

3

In [110]:
np.random.randint(low=10, high=101)

82

In [111]:
np.random.randint(low=10, high=101, size=10)

array([36, 76, 62, 77, 71, 24, 14, 77, 21, 96])

In [121]:
np.random.choice([4, 6, 10, 2])

np.int64(6)

In [127]:
np.random.choice(["python", "java", "sql"])

np.str_('sql')

In [129]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.random.shuffle(data)

In [132]:
data

array([9, 7, 8, 6, 1, 2, 0, 3, 4, 5])

### <a name='a6'></a> Podstawowe funkcje

In [134]:
np.exp(1)

np.float64(2.718281828459045)

In [135]:
np.sqrt(4)

np.float64(2.0)

In [136]:
np.all([2, 3, 1])

np.True_

In [137]:
np.any([0, 0, 1])

np.True_

In [138]:
bool(1)

True

In [140]:
x = np.random.rand(5)
x

array([0.934214  , 0.61396596, 0.5356328 , 0.58990998, 0.73012203])

In [141]:
np.argmax(x)

np.int64(0)

In [143]:
x[np.argmax(x)]

np.float64(0.9342139979247938)

In [144]:
np.argmin(x)

np.int64(2)

In [147]:
np.argsort(x)

array([2, 3, 1, 4, 0])

In [148]:
np.max(x)

np.float64(0.9342139979247938)

In [149]:
np.min(x)

np.float64(0.5356328030249583)

In [150]:
np.mean(x)

np.float64(0.6807689525573977)

In [151]:
np.median(x)

np.float64(0.613965955965896)

In [152]:
np.std(x)

np.float64(0.14174104066075693)

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [155]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [156]:
x[2]

np.int64(2)

In [157]:
x[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [158]:
x[:2]

array([0, 1])

In [160]:
x[[0,2]]

array([0, 2])

In [161]:
x[-1]

np.int64(19)

In [162]:
x[10:15]

array([10, 11, 12, 13, 14])

In [163]:
x = x.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [168]:
x[1:3,1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [171]:
x[2, 4] = 99

In [172]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 99],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [173]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 99],
       [15, 16, 17, 18, 19]])

In [174]:
for row in x:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 99]
[15 16 17 18 19]


In [175]:
for row in x:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [178]:
for item in x.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
99
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [179]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 99],
       [15, 16, 17, 18, 19]])

In [180]:
x.shape

(4, 5)

In [181]:
x.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 99, 15],
       [16, 17, 18, 19]])

In [183]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 99, 15, 16,
       17, 18, 19])

In [184]:
x.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 99, 19]])

### <a name='a10'></a> Maski logiczne

In [189]:
x = np.arange(start = -10, stop = 10, step = 0.5)
x = x.reshape(10, -1)
x

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [190]:
x > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [191]:
x[x > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [192]:
np.bitwise_and(x > 0, x < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [193]:
np.bitwise_or(x > 0, x < 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])